# Generated by Django 5.2.9 on 2025-12-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuildSettings',
            fields=[
                ('guild_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild_name', models.CharField(blank=True, max_length=100)),
                ('inactivity_days', models.PositiveIntegerField(default=14)),
                ('auto_kick_enabled', models.BooleanField(default=True)),
                ('inactivity_notifications_enabled', models.BooleanField(default=True)),
                ('afk_system_enabled', models.BooleanField(default=True)),
                ('quiet_ping_enabled', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
