# Generated by Django 5.2.9 on 2025-12-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildsettings',
            name='afk_approval_channel_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='bug_reports_channel_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='staff_role_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='support_category_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='ticket_panel_channel_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='ticket_panel_description',
            field=models.TextField(default='To create a ticket click 📩 below.'),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='ticket_panel_title',
            field=models.CharField(default='Ticket', max_length=100),
        ),
        migrations.AddField(
            model_name='guildsettings',
            name='tickets_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
